# Generated by Django 2.2.2 on 2019-07-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mulu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='pic',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
