# Generated by Django 2.2.2 on 2019-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mulu', '0002_furniture_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='mulu/static/photo/'),
        ),
    ]
