# Generated by Django 2.2.2 on 2019-07-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mulu', '0004_auto_20190709_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y%m%d'),
        ),
    ]
