# Generated by Django 2.2.2 on 2019-07-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mulu', '0006_auto_20190709_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture_detail_photos',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mulu.furniture'),
        ),
    ]
