# Generated by Django 2.2.2 on 2019-07-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mulu', '0007_auto_20190709_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture_detail_photos',
            old_name='files',
            new_name='file',
        ),
    ]
